name: Server
form: ~/plugins/dilexus/deploy/models/server/fields.yaml
modelClass: Dilexus\Deploy\Models\Server

create:
  title: Add Server
  redirect: dilexus/deploy/servers/update/:id
  redirectClose: dilexus/deploy/servers

update:
  title: Edit Server
  redirect: dilexus/deploy/servers
  redirectClose: dilexus/deploy/servers

preview:
  title: View Server
