modelClass: Dilexus\Deploy\Models\Server
title: Manage Servers
list: ~/plugins/dilexus/deploy/models/server/columns.yaml
recordUrl: dilexus/deploy/servers/update/:id

toolbar:
  buttons: list_toolbar
  search:
    prompt: Search servers...

defaultSort:
  column: name
  direction: asc
